--- 
addons: 
  apt: 
    packages: 
      - g++-4.8
    sources: 
      - ubuntu-toolchain-r-test
before_script: 
  - "bower install"
env: 
  - CXX=g++-4.8
language: node_js
node_js: 
  - "4.2"
script: 
  - "npm run tslint"
