language: node_js
node_js:
  - "4.2"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install --global typescript
  - npm install --global typings
  - npm install --global bower
  - npm run install && npm run tslint && npm run tslint && npm run tsc && npm run dist

script:
  - npm run test
